### ISSUE TITLE
清理资源后出现乱码显现！

### ISSUE THREAD

**Issue by Lonestar007** [NashLegend/AndroidResourceCleaner#1]
String中的文字乱码
android api 4.4.2/eclipse mars /window

**Comment by Lonestar007** [comment]
![image](https://cloud.githubusercontent.com/assets/5463843/12283860/af27fbc4-b9e5-11e5-8d1d-efba3d02ea9d.png)

**Comment by NashLegend** [comment]
你的项目目测不是UTF-8
